Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 13
"GET /dice/ HTTP/1.1" 200 1
"GET /dice/ HTTP/1.1" 200 1
"GET /dice/ HTTP/1.1" 200 1
"GET /dice/ HTTP/1.1" 200 1
"GET /dice/ HTTP/1.1" 200 1
"GET /dice/ HTTP/1.1" 200 1
"GET /dice/ HTTP/1.1" 200 1
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 13
1
"GET /dice/ HTTP/1.1" 200 1
5
"GET /dice/ HTTP/1.1" 200 1
6
"GET /dice/ HTTP/1.1" 200 1
2
"GET /dice/ HTTP/1.1" 200 1
1
"GET /dice/ HTTP/1.1" 200 1
5
"GET /dice/ HTTP/1.1" 200 1
5
"GET /dice/ HTTP/1.1" 200 1
3
"GET /dice/ HTTP/1.1" 200 1
5
"GET /dice/ HTTP/1.1" 200 1
4
"GET /dice/ HTTP/1.1" 200 1
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 165
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 186
"GET / HTTP/1.1" 200 186
"GET / HTTP/1.1" 200 186
"GET / HTTP/1.1" 200 186
"GET / HTTP/1.1" 200 186
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 195
"GET / HTTP/1.1" 200 195
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 208
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 8
"GET /about/ HTTP/1.1" 200 8
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 208
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2942
"GET / HTTP/1.1" 200 208
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 208
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /dice/dice/5
"GET /dice/dice/5 HTTP/1.1" 404 2942
Not Found: /dice/coin/10
"GET /dice/coin/10 HTTP/1.1" 404 2945
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myproject\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /coin/10
"GET /coin/10 HTTP/1.1" 404 2930
Not Found: /coin/10
"GET /coin/10 HTTP/1.1" 404 2930
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\urls.py changed, reloading.
Watching for file changes with StatReloader
Head
Internal Server Error: /coin/10
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: dice_coinflip

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\views.py", line 12, in coin
    CoinFlip(side=result).save()
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: dice_coinflip
"GET /coin/10 HTTP/1.1" 500 145079
Watching for file changes with StatReloader
Head
Internal Server Error: /coin/10
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\views.py", line 18, in coin
    return render(request, 'dice/dice.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dice/dice.html
"GET /coin/10 HTTP/1.1" 500 80779
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\views.py changed, reloading.
Watching for file changes with StatReloader
Tails
"GET /coin/10 HTTP/1.1" 200 348
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\models.py changed, reloading.
Watching for file changes with StatReloader
Head
"GET /coin/10 HTTP/1.1" 200 651
Tails
"GET /coin/10 HTTP/1.1" 200 786
Watching for file changes with StatReloader
Head
"GET /coin/10 HTTP/1.1" 200 810
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py", line 7, in main
    return render(request, 'main.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main.html
"GET / HTTP/1.1" 500 79740
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2965
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py", line 7, in main
    return render(request, 'main.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main.html
"GET / HTTP/1.1" 500 79740
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py", line 7, in main
    return render(request, 'main.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main.html
"GET / HTTP/1.1" 500 79739
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 287
Not Found: /main
"GET /main HTTP/1.1" 404 2944
Watching for file changes with StatReloader
Not Found: /main
"GET /main HTTP/1.1" 404 2944
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py", line 12, in about
    return render(request, 'abot+me.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: abot+me.html
"GET /about/ HTTP/1.1" 500 79357
Not Found: /main
"GET /main HTTP/1.1" 404 2944
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 288
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py", line 12, in about
    return render(request, 'abot+me.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: abot+me.html
"GET /about/ HTTP/1.1" 500 79357
Not Found: /index
"GET /index HTTP/1.1" 404 2947
Watching for file changes with StatReloader
Not Found: /index
"GET /index HTTP/1.1" 404 2947
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py", line 12, in about
    return render(request, 'abot+me.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busle\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: abot+me.html
"GET /about/ HTTP/1.1" 500 79357
Not Found: /index
"GET /index HTTP/1.1" 404 2947
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 288
"GET / HTTP/1.1" 200 288
"GET /about/ HTTP/1.1" 200 248
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 2965
Not Found: /about/about
"GET /about/about HTTP/1.1" 404 2965
"GET /about/ HTTP/1.1" 200 248
Not Found: /index
"GET /index HTTP/1.1" 404 2947
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 288
"GET /about/ HTTP/1.1" 200 248
Not Found: /about/about
"GET /about/about HTTP/1.1" 404 2965
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 288
"GET /index HTTP/1.1" 200 288
"GET /index HTTP/1.1" 200 288
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
"GET /index HTTP/1.1" 200 288
"GET /index HTTP/1.1" 200 288
"GET /index HTTP/1.1" 200 288
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /about/ HTTP/1.1" 200 252
Not Found: /about/about
"GET /about/about HTTP/1.1" 404 3130
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3130
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3130
"GET /about/ HTTP/1.1" 200 252
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3130
"GET /about/ HTTP/1.1" 200 252
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3130
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3129
"GET / HTTP/1.1" 200 288
"GET /index HTTP/1.1" 200 288
"GET /index HTTP/1.1" 200 288
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
C:\Users\busle\PycharmProjects\pythonProject3\myproject\dice\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 288
"GET /about/ HTTP/1.1" 200 252
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3130
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 288
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 284
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
"GET /index HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
Not Found: /about/
"GET /about/ HTTP/1.1" 404 3114
C:\Users\busle\PycharmProjects\pythonProject3\myproject\myapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 284
"GET /index HTTP/1.1" 200 284
"GET /about/ HTTP/1.1" 200 248
Not Found: /about/index
"GET /about/index HTTP/1.1" 404 3130
